# Generated by Django 3.2.9 on 2021-11-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='hinh',
            field=models.ImageField(default=None, upload_to='static/hinh/sanpham'),
        ),
    ]
