# Generated by Django 3.2.9 on 2021-11-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClothApp', '0002_sanpham_hinh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sanpham',
            name='hinh',
        ),
    ]
